spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/unicom?serverTimezone=GMT%2B8
    username: root
    password: 307314
#mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true


server:
  servlet:
    context-path: /unicom
  port: 314


#
hadoop:
  hdfs:
    hostname: localhost
    port: 8020
    username: root
hbase:
  addr: localhost:60000

